version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_container.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start_container.sh
      timeout: 300
      runas: ubuntu